name: Publish Docker image

# on:
#   push:
#     tags:
#       - "v*"

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build project
        run: |
          make build && make release
      # - name: Release
      #   run: go run tools/release/main.go
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
  # homebrew:
  #   name: Bump Homebrew formula
  #   needs: push_to_registry
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: dawidd6/action-homebrew-bump-formula@v3
  #       with:
  #         token: ${{secrets.HOMEBREW_GITHUB_TOKEN}}
  #         tap: di-graph/homebrew-digraph
  #         formula: digraph