name: run-go-tests
on:
  push:
    branches:
      - main
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  setup-test:
    name: Setup and test
    defaults:
      run:
        working-directory: ./
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Dependency cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('./go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Test
      run: go test ./...
